name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clean Buildozer Cache Permissions
        run: |
          sudo rm -rf ~/.buildozer
          sudo mkdir -p ~/.buildozer
          sudo chown -R $USER:$USER ~/.buildozer

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-11-jdk autoconf libtool libltdl-dev \
            pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
            cmake libffi-dev libssl-dev automake build-essential ccache lld

      - name: Install Compatible Pip & Buildozer
        run: |
          python -m pip install --upgrade setuptools wheel
          pip install pip==24.0
          pip install cython==0.29.33 buildozer

      - name: Run Buildozer
        run: |
          buildozer -v android debug
        env:
          PYTHONUNBUFFERED: 1
          CFLAGS: "-Wno-error=format-security -Wno-error=implicit-function-declaration"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AxiomAPK
          path: bin/*.apk
